### ISSUE TITLE
example Mikrotik IPFIX packets which result in parsing error

### ISSUE THREAD

**Issue by karel-un** [mikemiles-dev/netflow_parser#37]
I have grepped some error log messages with example packets which result in parsing error as asked in #28.

[v10_errors.txt](https://github.com/mikemiles-dev/netflow_parser/files/14637989/v10_errors.txt)

As you can see, they are from several devices and do not appear much often, on average each 10 seconds. Considering that server parse around 5000 IPFIX packets per second they are very rare.

Hope it will help.

**Comment by mikemiles-dev** [comment]
Do you have the template information for these sets?
