### ISSUE TITLE
v9 packets containing FLOW_LABEL are not parsable

### ISSUE THREAD

**Issue by arckoor** [mikemiles-dev/netflow_parser#69]
When parsing Ipv6 flows that contain a `FLOW_LABEL` record, the parser breaks (see template and data #262 in [this packet](https://github.com/user-attachments/files/15859485/bad-flow-label.pcapng.gz))

`FLOW_LABEL` is number 31, which currently is an [`UnsignedDataNumber`](https://github.com/mikemiles-dev/netflow_parser/blob/main/src/variable_versions/v9_lookup.rs#L165).
This tries to parse [based on field length](https://github.com/mikemiles-dev/netflow_parser/blob/main/src/variable_versions/common.rs#L45), but since the field is 3 bytes long, the parser errors for that packet.

**Comment by mikemiles-dev** [comment]
I will have a synopsis on this in a couple hours .

**Comment by mikemiles-dev** [comment]
Ok, Added version 0.3.4 with 3 byte DataNumber support.  Apologies for this oversight.
