### ISSUE TITLE
bug: PostNatdestinationIpv4address => PostNatsourceIpv4address

### ISSUE THREAD

**Issue by karel-un** [mikemiles-dev/netflow_parser#7]
https://github.com/mikemiles-dev/netflow_parser/blob/2cd911f585120414417fedf36339a512751deaf2/src/variable_versions/ipfix_lookup.rs#L1196

**Comment by abrugh** [comment]
also...
394 maps to SelectorIdTotalPktsObserved but it should be selectorIDTotalFlowsObserved
395 maps to SelectorIdTotalPktsSelected but it should be selectorIDTotalFlowsSelected
501 maps to SrhSegmentIpv6listSection but it should be srhSegmentIPv6LocatorLength

**Comment by mikemiles-dev** [comment]
https://github.com/mikemiles-dev/netflow_parser/pull/8

**Comment by mikemiles-dev** [comment]
Give this a look.  If acceptable I can merge, tag, and cargo publish tonight.

**Comment by karel-un** [comment]
Field 225 fix is trivial and I already fixed and tested it localy. But I am not sure about other fields.

@abrugh   ?
