### ISSUE TITLE
feature: support Post NAT fields in NetFlow v9

### ISSUE THREAD

**Issue by karel-un** [mikemiles-dev/netflow_parser#72]
Mike would you be so kind and add Post NAT fields to NetFlow v9 parser, specifically I need:

Mapped Flow ID Fields (L3 IPv4)

```
225  NF_F_XLATE_SRC_ADDR_IPV4    Post NAT Source IPv4 Address
226  NF_F_XLATE_DST_ADDR_IPV4    Post NAT Destination IPv4 Address
227  NF_F_XLATE_SRC_PORT         Post NAT Source Transport Port
228  NF_F_XLATE_DST_PORT         Post NAT Destination Transport Port
```

see

https://www.cisco.com/c/en/us/td/docs/security/asa/special/netflow/asa_netflow.html

**Comment by mikemiles-dev** [comment]
https://github.com/mikemiles-dev/netflow_parser/pull/73 Does this work?

**Comment by karel-un** [comment]
I am leaving for vacation in an hour, will be back for testing in a week. Thanks for fast reply!

**Comment by mikemiles-dev** [comment]
> I am leaving for vacation in an hour, will be back for testing in a week. Thanks for fast reply!

Did you have a chance to look at this?

**Comment by karel-un** [comment]
Testing right now, new v9 fields apparently work. Thanks!
